import { Card, CardContent, CardHeader, CardTitle, CardDescription, CardFooter } from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import { Copy, Check, Send } from "lucide-react";
import { useState } from "react";

export function DraftResponseEditor({
  draftContent,
  isAnalyzed,
}: {
  draftContent: string | undefined;
  isAnalyzed: boolean;
}) {
  const [copied, setCopied] = useState(false);
  const [content, setContent] = useState(draftContent || "");

  // Update editor if analysis finishes after initial render
  if (draftContent && draftContent !== content && !isAnalyzed) {
    setContent(draftContent);
  }

  const handleCopy = () => {
    navigator.clipboard.writeText(content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <Card className="flex flex-col h-full">
      <CardHeader>
        <CardTitle>AI Draft Response</CardTitle>
        <CardDescription>Generated by AI based on company policy and sentiment</CardDescription>
      </CardHeader>
      <CardContent className="flex-1">
        {isAnalyzed ? (
          <Textarea 
            className="min-h-[300px] h-full resize-none font-mono text-sm leading-relaxed"
            value={content || draftContent}
            onChange={(e) => setContent(e.target.value)}
          />
        ) : (
          <div className="h-[300px] flex items-center justify-center text-muted-foreground border rounded-md border-dashed">
            Trigger AI Analysis to generate a response draft.
          </div>
        )}
      </CardContent>
      {isAnalyzed && (
        <CardFooter className="flex justify-between border-t p-4">
          <Button variant="outline" onClick={handleCopy}>
            {copied ? <Check className="mr-2 h-4 w-4" /> : <Copy className="mr-2 h-4 w-4" />}
            {copied ? "Copied" : "Copy to Clipboard"}
          </Button>
          <Button>
            <Send className="mr-2 h-4 w-4" /> Approve & Send
          </Button>
        </CardFooter>
      )}
    </Card>
  )
}
