# Generated by Django 6.0.3 on 2026-03-22 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('channel', models.CharField(choices=[('Mobile App', 'Mobile App'), ('Email', 'Email'), ('WhatsApp', 'WhatsApp'), ('IVR', 'IVR'), ('In-Branch', 'In-Branch'), ('Social Media', 'Social Media')], max_length=50)),
                ('account_type', models.CharField(max_length=100)),
                ('raw_text', models.TextField()),
                ('actual_priority', models.CharField(choices=[('Urgent', 'Urgent'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=20)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DuplicateGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_tag', models.CharField(max_length=100, unique=True)),
                ('root_cause_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('Loan', 'Loan'), ('Card', 'Card'), ('Digital', 'Digital'), ('Branch', 'Branch'), ('Fraud', 'Fraud'), ('General', 'General')], max_length=50)),
                ('product', models.CharField(blank=True, max_length=100)),
                ('sentiment', models.CharField(blank=True, choices=[('Positive', 'Positive'), ('Neutral', 'Neutral'), ('Negative', 'Negative'), ('Hostile', 'Hostile')], max_length=20)),
                ('ai_priority', models.CharField(blank=True, max_length=20)),
                ('sla_hours', models.IntegerField(default=24)),
                ('sla_deadline', models.DateTimeField(blank=True, null=True)),
                ('cluster_tag', models.CharField(blank=True, max_length=100)),
                ('ai_draft', models.TextField(blank=True)),
                ('analyzed_at', models.DateTimeField(auto_now=True)),
                ('complaint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='complaints.complaint')),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='complaints.complaint')),
            ],
        ),
    ]
